#dependencies
install.packages("stringr")
install.packages("table1")
install.packages("dplyr")
install.packages("knitr")
install.packages("devtools")
install.packages("gridExtra")
install.packages("BiocManager")
install.packages("openxlsx")
install.packages("RCircos")
install.packages("webshot")
install.packages("psych")
install.packages("data.table")
BiocManager::install("karyoploteR", force = TRUE, dependencies = TRUE)
devtools::install_github('Mikata-Project/ggthemr')
webshot::install_phantomjs()